default_platform :ios

platform :ios do
  desc "Test"
  lane :test do
    # Run Tests, copying the raw logs to the project folder 
    scan(
    	scheme: "AudioRecorder",
    	buildlog_path: "./build/tests_log"
    )

    # Build the app without archiving, copying the raw logs to the project folder 
    sh("mkdir -p ./build")
    sh("touch ./build/build_log")
    sh("xcodebuild -workspace ./AudioRecorder.xcworkspace -scheme AudioRecorder 2>&1 | tee ./build/build_log")

    # Run SwiftInfo
    sh("../Pods/SwiftInfo/swiftinfo")

    # Commit and push SwiftInfo's result
    # sh("git add ../SwiftInfo-output/SwiftInfoOutput.json")
    # sh("git commit -m \"[ci skip] Updating SwiftInfo Output JSON\"")
    push_to_git_remote
  end
end
