default_platform :ios

platform :ios do
  desc "Test"
  lane :info do
    # Run Tests, copying the raw logs to the project folder 
    scan(
    	scheme: "CI",
    	buildlog_path: "./build/tests_log"
    )

    # Build the app without archiving, copying the raw logs to the project folder 
    sh("mkdir -p ./build")
    sh("touch ./build/build_log")
    sh("xcodebuild -project ../AudioRecorder.xcodeproj -scheme CI -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 2>&1 | tee ./build/build_log")

    # Run SwiftInfo
    sh("../swiftinfo/bin/swiftinfo ")

    # Commit and push SwiftInfo's result
    sh("git add ../SwiftInfo-output/SwiftInfoOutput.json")
    sh("git commit -m \"[ci skip] Updating SwiftInfo Output JSON\"")
  end
end