name: Danger

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ master ]
   
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: MeilCli/danger-action@v5
        with:
            plugins_file: 'Gemfile'
            danger_file: 'danger/Dangerfile'
            danger_id: 'danger-pr'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
